# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/Venv_projects/sys_info/ui/sys_info.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        font = QtGui.QFont()
        font.setPointSize(-1)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color:#B5C7CC; font-size:16px;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(120, 80, 521, 621))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_cpu_name_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_cpu_name_2.setStyleSheet("background-color:#8BA1AD;color:white;")
        self.lbl_cpu_name_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_cpu_name_2.setObjectName("lbl_cpu_name_2")
        self.gridLayout.addWidget(self.lbl_cpu_name_2, 6, 0, 1, 1)
        self.lbl_av_ram = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_av_ram.setStyleSheet("background-color:#8BA1AD;color:white;")
        self.lbl_av_ram.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_av_ram.setObjectName("lbl_av_ram")
        self.gridLayout.addWidget(self.lbl_av_ram, 4, 1, 1, 1)
        self.lbl_sys_ver = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_sys_ver.setStyleSheet("background-color:#8BA1AD;color:white;")
        self.lbl_sys_ver.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_sys_ver.setObjectName("lbl_sys_ver")
        self.gridLayout.addWidget(self.lbl_sys_ver, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setStyleSheet("background-color:#8BA1AD;color:white;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setStyleSheet("background-color:#8BA1AD;color:white;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setStyleSheet("background-color:#8BA1AD;color:white;")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 0, 1, 1)
        self.lbl_ram_usage = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_ram_usage.setStyleSheet("background-color:#8BA1AD;color:white;")
        self.lbl_ram_usage.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_ram_usage.setObjectName("lbl_ram_usage")
        self.gridLayout.addWidget(self.lbl_ram_usage, 5, 1, 1, 1)
        self.lbl_cpu_family = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_cpu_family.setStyleSheet("background-color:#8BA1AD;color:white;")
        self.lbl_cpu_family.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_cpu_family.setObjectName("lbl_cpu_family")
        self.gridLayout.addWidget(self.lbl_cpu_family, 2, 1, 1, 1)
        self.lbl_sys_name = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lbl_sys_name.setFont(font)
        self.lbl_sys_name.setStyleSheet("background-color:#8BA1AD;color:white;")
        self.lbl_sys_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_sys_name.setObjectName("lbl_sys_name")
        self.gridLayout.addWidget(self.lbl_sys_name, 0, 1, 1, 1)
        self.lbl_cpu_name = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_cpu_name.setStyleSheet("background-color:#8BA1AD;color:white;")
        self.lbl_cpu_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_cpu_name.setObjectName("lbl_cpu_name")
        self.gridLayout.addWidget(self.lbl_cpu_name, 6, 1, 1, 1)
        self.lbl_cpu_usage = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_cpu_usage.setStyleSheet("background-color:#8BA1AD;color:white;")
        self.lbl_cpu_usage.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_cpu_usage.setObjectName("lbl_cpu_usage")
        self.gridLayout.addWidget(self.lbl_cpu_usage, 7, 1, 1, 1)
        self.lbl_total_ram = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_total_ram.setStyleSheet("background-color:#8BA1AD;color:white;")
        self.lbl_total_ram.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_total_ram.setObjectName("lbl_total_ram")
        self.gridLayout.addWidget(self.lbl_total_ram, 3, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setStyleSheet("background-color:#8BA1AD;color:white;")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color:#8BA1AD;color:white;")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setStyleSheet("background-color:#8BA1AD;color:white;")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 0, 1, 1)
        self.dsfds = QtWidgets.QLabel(self.gridLayoutWidget)
        self.dsfds.setStyleSheet("background-color:#8BA1AD;color:white;")
        self.dsfds.setAlignment(QtCore.Qt.AlignCenter)
        self.dsfds.setObjectName("dsfds")
        self.gridLayout.addWidget(self.dsfds, 5, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(740, 80, 431, 621))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_41 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_41.setStyleSheet("background-color:#8BA1AD;color:white;")
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout_2.addWidget(self.label_41, 7, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_42.setStyleSheet("background-color:#8BA1AD;color:white;")
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.gridLayout_2.addWidget(self.label_42, 6, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_45.setStyleSheet("background-color:#8BA1AD;color:white;")
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.gridLayout_2.addWidget(self.label_45, 1, 0, 1, 1)
        self.lbl_gpu_name = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lbl_gpu_name.setStyleSheet("background-color:#8BA1AD;color:white;")
        self.lbl_gpu_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_gpu_name.setObjectName("lbl_gpu_name")
        self.gridLayout_2.addWidget(self.lbl_gpu_name, 3, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_38.setStyleSheet("background-color:#8BA1AD;color:white;")
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.gridLayout_2.addWidget(self.label_38, 2, 0, 1, 1)
        self.lbl_battery_per = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lbl_battery_per.setStyleSheet("background-color:#8BA1AD;color:white;")
        self.lbl_battery_per.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_battery_per.setObjectName("lbl_battery_per")
        self.gridLayout_2.addWidget(self.lbl_battery_per, 2, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_36.setStyleSheet("background-color:#8BA1AD;color:white;")
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.gridLayout_2.addWidget(self.label_36, 3, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_37.setStyleSheet("background-color:#8BA1AD;color:white;")
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.gridLayout_2.addWidget(self.label_37, 4, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_39.setStyleSheet("background-color:#8BA1AD;color:white;")
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.gridLayout_2.addWidget(self.label_39, 5, 0, 1, 1)
        self.lbl_vram = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lbl_vram.setStyleSheet("background-color:#8BA1AD;color:white;")
        self.lbl_vram.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_vram.setObjectName("lbl_vram")
        self.gridLayout_2.addWidget(self.lbl_vram, 5, 1, 1, 1)
        self.lbl_cpu_temp = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lbl_cpu_temp.setStyleSheet("background-color:#8BA1AD;color:white;")
        self.lbl_cpu_temp.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_cpu_temp.setObjectName("lbl_cpu_temp")
        self.gridLayout_2.addWidget(self.lbl_cpu_temp, 1, 1, 1, 1)
        self.lbl_gpu_driver = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lbl_gpu_driver.setStyleSheet("background-color:#8BA1AD;color:white;")
        self.lbl_gpu_driver.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_gpu_driver.setObjectName("lbl_gpu_driver")
        self.gridLayout_2.addWidget(self.lbl_gpu_driver, 4, 1, 1, 1)
        self.lbl_vram_usage = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lbl_vram_usage.setStyleSheet("background-color:#8BA1AD;color:white;")
        self.lbl_vram_usage.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_vram_usage.setObjectName("lbl_vram_usage")
        self.gridLayout_2.addWidget(self.lbl_vram_usage, 6, 1, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_59.setStyleSheet("background-color:#8BA1AD;color:white;")
        self.label_59.setAlignment(QtCore.Qt.AlignCenter)
        self.label_59.setObjectName("label_59")
        self.gridLayout_2.addWidget(self.label_59, 0, 0, 1, 1)
        self.lbl_usage_vram_per = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lbl_usage_vram_per.setStyleSheet("background-color:#8BA1AD;color:white;")
        self.lbl_usage_vram_per.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_usage_vram_per.setObjectName("lbl_usage_vram_per")
        self.gridLayout_2.addWidget(self.lbl_usage_vram_per, 7, 1, 1, 1)
        self.lbl_cpu_count = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lbl_cpu_count.setStyleSheet("background-color:#8BA1AD;color:white;")
        self.lbl_cpu_count.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_cpu_count.setObjectName("lbl_cpu_count")
        self.gridLayout_2.addWidget(self.lbl_cpu_count, 0, 1, 1, 1)
        self.lbl_dev_name = QtWidgets.QLabel(self.centralwidget)
        self.lbl_dev_name.setGeometry(QtCore.QRect(-10, 20, 1301, 39))
        self.lbl_dev_name.setStyleSheet("font-size:22px;")
        self.lbl_dev_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_dev_name.setObjectName("lbl_dev_name")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 60, 1231, 651))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.widget.setFont(font)
        self.widget.setStyleSheet("background-color:#8BA1AD; border-radius: 50px 50px 0 50px;")
        self.widget.setObjectName("widget")
        self.widget.raise_()
        self.gridLayoutWidget.raise_()
        self.gridLayoutWidget_2.raise_()
        self.lbl_dev_name.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "System Info"))
        self.lbl_cpu_name_2.setText(_translate("MainWindow", "CPU:"))
        self.lbl_av_ram.setText(_translate("MainWindow", "NONE"))
        self.lbl_sys_ver.setText(_translate("MainWindow", "NONE"))
        self.label_5.setText(_translate("MainWindow", "CPU USAGE (%):"))
        self.label.setText(_translate("MainWindow", "AV. RAM:"))
        self.label_10.setText(_translate("MainWindow", "TOTAL RAM:"))
        self.lbl_ram_usage.setText(_translate("MainWindow", "NONE"))
        self.lbl_cpu_family.setText(_translate("MainWindow", "NONE"))
        self.lbl_sys_name.setText(_translate("MainWindow", "NONE"))
        self.lbl_cpu_name.setText(_translate("MainWindow", "NONE"))
        self.lbl_cpu_usage.setText(_translate("MainWindow", "NONE"))
        self.lbl_total_ram.setText(_translate("MainWindow", "NONE"))
        self.label_12.setText(_translate("MainWindow", "SYSTEM VER:"))
        self.label_13.setText(_translate("MainWindow", "SYSTEM:"))
        self.label_11.setText(_translate("MainWindow", "CPU FAMILY:"))
        self.dsfds.setText(_translate("MainWindow", "RAM USAGE (%):"))
        self.label_41.setText(_translate("MainWindow", "USAGE GPU(%):"))
        self.label_42.setText(_translate("MainWindow", "USAGE VRAM:"))
        self.label_45.setText(_translate("MainWindow", "CPU TEMP:"))
        self.lbl_gpu_name.setText(_translate("MainWindow", "NONE"))
        self.label_38.setText(_translate("MainWindow", "BATTERY(%):"))
        self.lbl_battery_per.setText(_translate("MainWindow", "NONE"))
        self.label_36.setText(_translate("MainWindow", "GPU:"))
        self.label_37.setText(_translate("MainWindow", "GPU DRIVER:"))
        self.label_39.setText(_translate("MainWindow", "VRAM:"))
        self.lbl_vram.setText(_translate("MainWindow", "NONE"))
        self.lbl_cpu_temp.setText(_translate("MainWindow", "NONE"))
        self.lbl_gpu_driver.setText(_translate("MainWindow", "NONE"))
        self.lbl_vram_usage.setText(_translate("MainWindow", "NONE"))
        self.label_59.setText(_translate("MainWindow", "CPU COUNT:"))
        self.lbl_usage_vram_per.setText(_translate("MainWindow", "NONE"))
        self.lbl_cpu_count.setText(_translate("MainWindow", "NONE"))
        self.lbl_dev_name.setText(_translate("MainWindow", "DEVICE  NAME"))

